from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
CAMBRIDGE_DIR = BASE_DIR / "Cambridge"
BOSTON_DIR = BASE_DIR / "Boston"

CAMBRIDGE_CRIME_CSV = CAMBRIDGE_DIR / "Crime_Reports_20250112.csv"
CAMBRIDGE_SHAPEFILE = CAMBRIDGE_DIR / "BOUNDARY_CDDNeighborhoods.shp" / "BOUNDARY_CDDNeighborhoods.shp"

BOSTON_CRIME_CSV = BOSTON_DIR / "Boston_Incidents_View_3136327856209597499.csv"
BOSTON_POP_XLSM = BOSTON_DIR / "2015-2019_neighborhood_tables_2021.12.21.xlsm"
BOSTON_SHAPEFILE = (
    BOSTON_DIR
    / "Boston_Neighborhood_Boundaries_Approximated_by_2020_Census_Block_Groups.shp"
)

CAMBRIDGE_POP_2020 = {
    "East Cambridge": 13246,
    "MIT": 6238,
    "Inman/Harrington": 6718,
    "Area 4": 7280,
    "Cambridgeport": 13083,
    "Mid-Cambridge": 13974,
    "Riverside": 12114,
    "Agassiz": 5146,
    "Peabody": 12471,
    "West Cambridge": 8450,
    "North Cambridge": 15372,
    "Highlands": 1646,
    "Strawberry Hill": 2665,
}

CAMBRIDGE_CRIME_MACROS = {
    "Aggravated Assault": "Violent Crime",
    "Homicide": "Violent Crime",
    "Kidnapping": "Violent Crime",
    "Simple Assault": "Violent Crime",
    "Stalking": "Violent Crime",
    "Street Robbery": "Violent Crime",
    "Threats": "Violent Crime",
    "Weapon Violations": "Violent Crime",
    "Arson": "Property Crime",
    "Auto Theft": "Property Crime",
    "Commercial Break": "Property Crime",
    "Commercial Robbery": "Property Crime",
    "Housebreak": "Property Crime",
    "Larceny (Misc)": "Property Crime",
    "Larceny from Building": "Property Crime",
    "Larceny from MV": "Property Crime",
    "Larceny from Person": "Property Crime",
    "Larceny from Residence": "Property Crime",
    "Larceny of Bicycle": "Property Crime",
    "Larceny of Plate": "Property Crime",
    "Larceny of Services": "Property Crime",
    "Mal. Dest. Property": "Property Crime",
    "Shoplifting": "Property Crime",
    "Drugs": "Drug Offense",
    "Counterfeiting": "White-Collar Crime",
    "Embezzlement": "White-Collar Crime",
    "Extortion/Blackmail": "White-Collar Crime",
    "Forgery": "White-Collar Crime",
    "Flim Flam": "White-Collar Crime",
    "Annoying & Accosting": "Public Order Crime",
    "Disorderly": "Public Order Crime",
    "Drinking in Public": "Public Order Crime",
    "Gambling": "Public Order Crime",
    "Noise Complaint": "Public Order Crime",
    "Peeping & Spying": "Public Order Crime",
    "Prostitution": "Public Order Crime",
    "Rec. Stol. Property": "Public Order Crime",
    "Trespassing": "Public Order Crime",
    "Accident": "Traffic Violation",
    "Hit and Run": "Traffic Violation",
    "Taxi Violation": "Traffic Violation",
    "OUI": "Traffic Violation",
    "Domestic Dispute": "Personal Crime",
    "Harassment": "Personal Crime",
    "Indecent Exposure": "Personal Crime",
    "Phone Calls": "Personal Crime",
    "Sex Offender Violation": "Personal Crime",
    "Violation of H.O.": "Protective Order Violation",
    "Violation of R.O.": "Protective Order Violation",
    "Admin Error": "Miscellaneous",
    "Liquor Possession/Sale": "Miscellaneous",
    "Missing Person": "Miscellaneous",
    "Suspicious Package": "Miscellaneous",
    "Warrant Arrest": "Miscellaneous",
}

CAMBRIDGE_NEIGHBORHOOD_NAME_MAP = {
    "The Port": "Area 4",
    "Neighborhood Nine": "Peabody",
    "Wellington-Harrington": "Inman/Harrington",
    "Mid-Cambridge": "Mid-Cambridge",
    "North Cambridge": "North Cambridge",
    "Cambridge Highlands": "Highlands",
    "Strawberry Hill": "Strawberry Hill",
    "West Cambridge": "West Cambridge",
    "Riverside": "Riverside",
    "Cambridgeport": "Cambridgeport",
    "Area 2/MIT": "MIT",
    "East Cambridge": "East Cambridge",
    "Baldwin": "Agassiz",
}

BOSTON_CRIME_MACROS = {
    "Aggravated Assault": "Violent Crime",
    "Homicide": "Violent Crime",
    "Simple Assault": "Violent Crime",
    "Indecent Assault": "Violent Crime",
    "Robbery": "Violent Crime",
    "Rape & Attempted": "Violent Crime",
    "Threats To Do Bodily Harm": "Violent Crime",
    "Murder, Non-Negligent Manslaughter": "Violent Crime",
    "Assault - Simple": "Violent Crime",
    "Assault - Aggravated": "Violent Crime",
    "Sex Offense - Rape - Forcible": "Violent Crime",
    "Sex Offense - Rape - Sodomy": "Violent Crime",
    "Fondling - Indecent Assault": "Violent Crime",
    "Human Trafficking": "Violent Crime",
    "Manslaughter": "Violent Crime",
    "Offenses Against Child / Family": "Violent Crime",
    "Weapon Violation - Carry/ Possessing/ Sale/ Traffi": "Violent Crime",
    "Arson": "Property Crime",
    "Auto Theft": "Property Crime",
    "Auto Theft - Leased/Rented Vehicle": "Property Crime",
    "Auto Theft - Motorcycle / Scooter": "Property Crime",
    "Auto Theft Recovery": "Property Crime",
    "Residential Burglary": "Property Crime",
    "Commercial Burglary": "Property Crime",
    "Burglary - Commerical": "Property Crime",
    "Larceny From Mv": "Property Crime",
    "Larceny Theft From Building": "Property Crime",
    "Other Larceny": "Property Crime",
    "Larceny Theft Of Bicycle": "Property Crime",
    "Larceny Shoplifting": "Property Crime",
    "Larceny Theft From Mv - Non-Accessory": "Property Crime",
    "Larceny All Others": "Property Crime",
    "Recovered Stolen Property": "Property Crime",
    "Property Found": "Property Crime",
    "Property Lost": "Property Crime",
    "Vandalism": "Property Crime",
    "Larceny Purse Snatch - No Force": "Property Crime",
    "Breaking And Entering (B&E) Motor Vehicle (No Prop": "Property Crime",
    "Recovered - Mv Recovered In Boston (Stolen In Bost": "Property Crime",
    "Larceny Theft Of Mv Parts & Accessories": "Property Crime",
    "Stolen Property - Buying / Receiving / Possessing": "Property Crime",
    "Possession Of Burglarious Tools": "Property Crime",
    "Property - Accidental Damage": "Property Crime",
    "Property Related Damage": "Property Crime",
    "Property - Found": "Property Crime",
    "Property - Lost Then Located": "Property Crime",
    "Property - Lost/ Missing": "Property Crime",
    "License Plate Related Incidents": "Property Crime",
    "Drug Violation": "Drug Offense",
    "Drugs - Possession/ Sale/ Manufacturing/ Use": "Drug Offense",
    "Drugs - Possession Of Drug Paraphanalia": "Drug Offense",
    "Sick Assist - Drug Related Illness": "Drug Offense",
    "Fraud": "White-Collar Crime",
    "Counterfeiting": "White-Collar Crime",
    "Embezzlement": "White-Collar Crime",
    "Confidence Games": "White-Collar Crime",
    "Forgery / Counterfeiting": "White-Collar Crime",
    "Fraud - Credit Card / Atm Fraud": "White-Collar Crime",
    "Fraud - False Pretense / Scheme": "White-Collar Crime",
    "Fraud - Wire": "White-Collar Crime",
    "Fraud - Welfare": "White-Collar Crime",
    "Identity Fraud C266.37E": "White-Collar Crime",
    "Disorderly Conduct": "Public Order Crime",
    "Prostitution": "Public Order Crime",
    "Trespassing": "Public Order Crime",
    "Liquor Violation": "Public Order Crime",
    "Noise Complaint": "Public Order Crime",
    "Bomb Hoax": "Public Order Crime",
    "Bomb Threat": "Public Order Crime",
    "Gambling": "Public Order Crime",
    "Dangerous Or Hazardous Condition": "Public Order Crime",
    "Assembly Or Gathering Violations": "Public Order Crime",
    "Disturbing The Peace/ Disorderly Conduct/ Gatherin": "Public Order Crime",
    "Explosives": "Public Order Crime",
    "Liquor Law Violation": "Public Order Crime",
    "Noisy Party/Radio-No Arrest": "Public Order Crime",
    "Violation - City Ordinance": "Public Order Crime",
    "Mv Crash Response": "Traffic Violation",
    "Operating Under The Influence": "Traffic Violation",
    "M/V Accident - Personal Injury": "Traffic Violation",
    "M/V Accident - Property Damage": "Traffic Violation",
    "M/V Accident - Involving Pedestrian - Injury": "Traffic Violation",
    "M/V Accident - Other": "Traffic Violation",
    "M/V - Leaving Scene - Property Damage": "Traffic Violation",
    "M/V - Leaving Scene - Personal Injury": "Traffic Violation",
    "M/V Accident - Involving Pedestrian - No Injury": "Traffic Violation",
    "M/V Accident - Other City Vehicle": "Traffic Violation",
    "M/V Accident - Police Vehicle": "Traffic Violation",
    "M/V Plates - Lost": "Traffic Violation",
    "Towed Motor Vehicle": "Traffic Violation",
    "M/V Accident - Involving Bicycle - Injury": "Traffic Violation",
    "M/V Accident - Involving Bicycle - No Injury": "Traffic Violation",
    "Towed": "Traffic Violation",
    "Val - Operating After Rev/Susp.": "Traffic Violation",
    "Val - Operating W/O Authorization Lawful": "Traffic Violation",
    "Val - Violation Of Auto Law": "Traffic Violation",
    "Operating Under The Influence (Oui) Alcohol": "Traffic Violation",
    "Verbal Disputes": "Personal Crime",
    "Verbal Dispute": "Personal Crime",
    "Criminal Harassment": "Personal Crime",
    "Harassment/ Criminal Harassment": "Personal Crime",
    "Sex Offender Registration": "Personal Crime",
    "Indecent Exposure/ Lewd And Lascivious/ Open And G": "Personal Crime",
    "Child Endangerment": "Personal Crime",
    "Failure To Register As A Sex Offender": "Personal Crime",
    "Phone Call Complaints": "Personal Crime",
    "Obscene Materials - Pornography": "Personal Crime",
    "Sex Offense - Other": "Personal Crime",
    "Sexual Assault Investigation": "Personal Crime",
    "Sexual Assault Kit Collected": "Personal Crime",
    "Restraining Order Violations": "Protective Order Violation",
    "Viol. Of Restraining Order W Arrest": "Protective Order Violation",
    "Violation - Restraining Order (No Arrest)": "Protective Order Violation",
    "Violation - Harassment Prevention Order": "Protective Order Violation",
    "Investigate Person": "Miscellaneous",
    "Investigate Property": "Miscellaneous",
    "Service": "Miscellaneous",
    "Search Warrants": "Miscellaneous",
    "Search Warrant": "Miscellaneous",
    "Missing Person Reported": "Miscellaneous",
    "Missing Person Located": "Miscellaneous",
    "Missing Person - Located": "Miscellaneous",
    "Missing Person - Not Reported - Located": "Miscellaneous",
    "Fire Related Reports": "Miscellaneous",
    "Fire Report": "Miscellaneous",
    "Fire Report/Alarm - False": "Miscellaneous",
    "Landlord/Tenant Disputes": "Miscellaneous",
    "Landlord - Tenant": "Miscellaneous",
    "Animal Incidents (Dog Bites, Lost Dog, Etc)": "Miscellaneous",
    "Animal Abuse": "Miscellaneous",
    "Death Investigation": "Miscellaneous",
    "Prisoner Related Incidents": "Miscellaneous",
    "Recovered - Mv Recovered In Boston (Stolen Outside": "Miscellaneous",
    "Aircraft": "Miscellaneous",
    "Evading Fare": "Miscellaneous",
    "Biological Threat": "Miscellaneous",
    "Sudden Death": "Miscellaneous",
    "Fugitive From Justice": "Miscellaneous",
    "Other": "Miscellaneous",
    "Other Offense": "Miscellaneous",
    "Ballistics": "Miscellaneous",
    "Ballistics Evidence/Found": "Miscellaneous",
    "Firearm Discovery": "Miscellaneous",
    "Firearm Violations": "Miscellaneous",
    "Firearm/Weapon - Found Or Confiscated": "Miscellaneous",
    "Harbor Incident / Violation": "Miscellaneous",
    "Harbor Related Incidents": "Miscellaneous",
    "License Premise Violation": "Miscellaneous",
    "License Violation": "Miscellaneous",
    "Medical Assistance": "Miscellaneous",
    "Missing Person": "Miscellaneous",
    "Police Service Incidents": "Miscellaneous",
    "Service To Other Agency": "Miscellaneous",
    "Sick Assist": "Miscellaneous",
    "Sick/Injured/Medical - Person": "Miscellaneous",
    "Sick/Injured/Medical - Police": "Miscellaneous",
    "Truancy / Runaway": "Miscellaneous",
    "Violations": "Miscellaneous",
    "Warrant Arrest - Boston Warrant (Must Be Supplemen": "Miscellaneous",
    "Warrant Arrest - Outside Of Boston Warrant": "Miscellaneous",
    "Warrant Arrests": "Miscellaneous",
}

BOSTON_NEIGHBORHOOD_NAME_MAP = {
    "Chinatown": "Downtown",
    "Leather District": "Downtown",
    "Bay Village": "South End",
}
